wechat_id: EyGameStudio #replace this with your wechat id
help_message: your help message
welcome_message:
  title: 广游汇工作室
  picture: http://tp4.sinaimg.cn/1923130343/180/40044228229/1
  description: 欢迎您关注广游汇工作室
  link: weibo.com/u/1923130343
